# Generated by Django 4.1.2 on 2023-06-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='numero_documento',
            field=models.IntegerField(unique=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_legajo',
            field=models.IntegerField(unique=True, verbose_name='Numero de legajo'),
        ),
    ]
