# Generated by Django 4.2.1 on 2023-06-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_coordinador_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservaservicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
    ]
